server:
  port: 8092

spring:
  rabbitmq:
    host: 47.113.**.37
    port: 5672
    virtual-host: /
    username: your_name
    password: your_password

mq:
  server:
    award: mq.dome.award
    rebate: mq.dome.rebate


